<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExcludeFacilities</name>
   <tag></tag>
   <elementGuidId>f1346daf-6a62-40da-830e-c2f60a7d5345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;EXCLUSIONS&quot;]//*[contains(text(),&quot;${excludefacilities}&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
