<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StarSelection</name>
   <tag></tag>
   <elementGuidId>a871baac-22ad-413e-89d9-8f118bd6f727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name=&quot;tourstars&quot;]//option[@value=&quot;${value}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
