<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerifyTourPresent</name>
   <tag></tag>
   <elementGuidId>b367f06c-e9a8-4a39-b90f-c62e6e1ff8f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/div/div[2]/div/div/div[1]/div[2]/table/tbody/tr[1]/td[5]</value>
   </webElementProperties>
</WebElementEntity>
