<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectApplier</name>
   <tag></tag>
   <elementGuidId>758c2e5a-c96b-45a2-825c-def6dac65320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;form-group&quot;]//*[contains(text(),&quot;${supplier}&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
